name: Test Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-latest
    steps:
      - name: Print to console
        run: echo Hello Github Actionc
      - name: Print a few lines
        run: |
          echo: Print text 1
          echo: Print text 2
