name: Test App
on: push
jobs:
  runs-on: windows-latest
  steps:
    - name: Get repository code
      # run
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
      # run: npm ci
