name: Test App
on:
  push:
    branches:
      - main # Гілка, яку ми хочемо тестувати

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        # run
      - name: Install dependencies
        run: npm install
        # run: npm ci
